language: python

os: linux

python: 3.8
  
env:
  global:  
  - APP_CONFIG='config.py'
  - SECRET_KEY='Fly'
  - API_KEY='wefwefwewegewgewgew'

install:
  - pip install -r requirements.txt

script:
   python -m unittest 

   
